apiVersion: v1
kind: ServiceAccount
metadata:
  name: sec-dashboard-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "2ef6d19e-e551-48fd-b332-5f2ca901c198"
  labels:
    azure.workload.identity/use: "true"
